### ISSUE TITLE
When NIGHTFALL?! :)

### ISSUE THREAD

**Issue by miki-bgd-011** [EYBlockchain/nightfall#1]
You said MAY, don't pull a bakkt please...

**Comment by 0zAND1z** [comment]
@Westlad , it would be great if we can have a date and plans for open sourcing the code.

We are very eagered to take a look at EY's efforts here & help wherever possible. Cheers.

**Comment by Chaitanya-Konda** [comment]
@miki-bgd-011 @0zAND1z Really good to hear your excitement. We are working on making the code as developer friendly as possible. To make it easier to understand and contribute. It will be made public this week mostly 🚀

**Comment by mkinney** [comment]
Release early and often.

**Comment by xoryouyou** [comment]
@Chaitanya-Konda developer onboarding is a continuous process. Don't fret about making it perfect the first time it will grow and improve with interaction once the community can see a few "Hello worlds".

**Comment by miki-bgd-011** [comment]
How embarrassing, JP Morgan beat you to it.

https://twitter.com/coindesk/status/1133282106392633344

**Comment by sogasg** [comment]
> How embarrassing, JP Morgan beat you to it.
> 
> https://twitter.com/coindesk/status/1133282106392633344

Where is the repo?

**Comment by miki-bgd-011** [comment]
"The New York-based financial institution will open-source the extension Tuesday"
JP Morgan doesn't fuck around with release announcements so it's coming TODAY!

**Comment by Westlad** [comment]
Nighfall will be published on the 31st May.

**Comment by JanKalin** [comment]
> 
> 
> > How embarrassing, JP Morgan beat you to it.
> > https://twitter.com/coindesk/status/1133282106392633344
> 
> Where is the repo?

https://github.com/jpmorganchase/anonymous-zether

But IMHO it's not embarassing, it's exhilerating! Two of the big four publishing the necessary tools to get anonymity on a public blockchain is something I didn't anticipate happening soon.

**Comment by innovator256** [comment]
💯

**Comment by 1blockologist** [comment]
@JanKalin  @miki-bgd-011  the JP Morgan solution only works for Ethereum transfers, and this seems to only work for transfers that inherit erc20

I would say the JP Morgan release pushed them to open source instead of "waiting till it was perfect", glad to see this
