### ISSUE TITLE
Factor out pcode preprocessor

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#118]
Currently a new language, pcode, is created and then preprocessed into code, the input for ZoKrates.

This is handled in https://github.com/EYBlockchain/nightfall/blob/master/zkp/code/tools-code-preprop.js

To increase readability and assurance, this preprocessor could be factored out (with test cases!) into a separate library. Effort is already started at https://github.com/EYBlockchain/zokrates-preprocessor

Upstream may have an interest to incorporate it into ZoKrates or at least we could maintain it at zokrates/zokrates-preprocessor for wider adoption.

**Comment by ChaitanyaKonda** [comment]
preprocessor code will be refactored into a folder under root directory. Redundant repository https://github.com/EYBlockchain/zokrates-preprocessor to be removed. 

The new refactored code can be called at setup stage or as a cli method.

**Comment by fulldecent** [comment]
This is obviated by https://github.com/EYBlockchain/nightfall/commit/4f47cdb1b79d3984d7574ba52094c5db51f7f7f8
