### ISSUE TITLE
Docker-compose: add dependencies for loose coupling

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#120]
Currently the module have interdependencies which are not defined in the docker-compose.yml.

For example, the API-gateway will communicate with the zkp module, this is defined at https://github.com/EYBlockchain/nightfall/blob/master/API-Gateway/src/config/config.js#L9-L11

But such a dependency is not defined as a `depends_on` at https://github.com/EYBlockchain/nightfall/blob/master/docker-compose.yml#L18-L27

The `depends_on` can be added here and any other such cases, if any, to improve clarity.

**Comment by vishnusudarshan** [comment]
This issue is addressed and created a PR for the same
https://github.com/EYBlockchain/nightfall/pull/233
Hence, closing the issue.
