### ISSUE TITLE
Outdated G2 library

### ISSUE THREAD

**Issue by musalbas** [EYBlockchain/nightfall#14]
This repo is using an outdated version of the Solidity BN256G2 library which has insufficient checks to make sure that all input points are on the curve in ECTwistAdd (the second point isn't checked), in https://github.com/EYBlockchain/nightfall/blob/master/zkp/contracts/Pairing_v1.sol.

For security reasons the library should be updated to either the latest version in ZoKrates (https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_core/src/proof_system/bn128/utils/solidity.rs) or https://github.com/musalbas/solidity-BN256G2/blob/master/BN256G2.sol (which has ~20,000 lower gas cost).

**Comment by iAmMichaelConnor** [comment]
Thanks very much for raising this. And thanks for the library!

**Comment by fulldecent** [comment]
For reference -- at this time the two links in original post now have the same code
