### ISSUE TITLE
Native Ganache Support

### ISSUE THREAD

**Issue by CruzMolina** [EYBlockchain/nightfall#154]
# Description

Currently, Nightfall integration with Ganache requires the use of the whisper stub (`whisper-controller-stub`). Whichever encryption protocol Nightfall decides to use moving forward should be tested against Ganache to ensure native support and integration.

Native Ganache support would **greatly** enhance the developer experience and support the creation of tutorials aimed at on-boarding developers to Nightfall.

**Comment by Westlad** [comment]
Unfortunately this isn't possible at the moment because Ganache does not support Whisper, so there is not possibility of native Ganache Support. That's why we use whisper-controller-stub to add the missing functionality.

**Comment by CruzMolina** [comment]
Hey @Westlad,

I'm under the impression the Nightfall development team is currently experimenting with using something other than Whisper for encryption purposes. Possibly a protocol and/or implementation that would be more compatible with Ganache.

cc @Mel-Marsollier

**Comment by fulldecent** [comment]
Hi Cruz, thank you for reaching out with this. I just sent you my contact information by email and hope we can catch up together to scope this out.

**Comment by Westlad** [comment]
@CruzMolina Yes, it's true we're looking at removing Whisper.  When we do that the application will support Ganache natively as a consequence (Whisper being the only issue).

**Comment by ChaitanyaKonda** [comment]
Closing this issue because #336 will remove Whisper at which point ganache will be natively supported
