### ISSUE TITLE
Add live network configuration options, offchain and zkp modules

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#157]
# BLOCKERS

- [ ] #167 Accounts module hardcodes a dependency on ganache host
- [ ] #168 Extract all host configurations options to Docker Compose environment variables

# Description

Add live network configuration options: offchain and zkp modules.

Reference https://www.trufflesuite.com/tutorials/deploying-to-the-live-network

#### System information

(Not relevant)

#### Expected behaviour

- [ ] Offchain module supports, via a configuration option, to choose between local development Ganache or live network environment
- [ ] Zkp module supports, via a configuration option, to choose between local development Ganache or live network environment

**Comment by fulldecent** [comment]
Some notes to self:

- We have some internal work started on this already. Parity "unlock acounts" uses different command line parameters than Geth. 
- Update docker to switch between whisper/stub
- Review differences between Whisper stub and https://github.com/paritytech/whisper

---

Follow on work
- [ ] Create Docker image to run Geth or Parity // use VOLUME to bring in local blockchain data

**Comment by LijuJoseJJ** [comment]
Hi @fulldecent 
PR #177 & PR #174 is resolving this issue for zkp and offchain microservice respectively.
and they merged now

**Comment by iAmMichaelConnor** [comment]
@fulldecent #167 & #168 appear to have now been handled. So I'll go ahead an close this issue. Please can you open a new issue relating to Parity Network Configuration if you so wish?

**Comment by fulldecent** [comment]
Excellent, thank you
