### ISSUE TITLE
Write and perform full integration test against Ropsten network

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#160]
# Description

Demonstrate that Nightfall network configuration choices work by performing a full integration test against the Ropsten network.

Notice from [the README](https://github.com/EYBlockchain/nightfall/blob/master/README.md): 

> Note that this code has not yet completed a security review and therefore we strongly recommend that you do not use it in production or to transfer items of material value. We take no responsibility for any loss you may incur through the use of this code.

---

It is possible that that issue may be satisfied by deploying in a way that is less secure than would be done in a production deployment. For example, the "toxic waste" for this deployment may be published. Such details and a full work scope will be determined and committed BEFORE such work on this issue commences.

#### System information

(Not applicable)

#### Expected behaviour

- [ ] Full integration test for connecting Nightfall to a public network is written, including a list of expected artifacts
- [ ] Full integration test is successfully performed with documentation of the expected artifacts

**Comment by ChaitanyaKonda** [comment]
Closing this issue as nightfall was deployed to the main net for demo purposes.
The ERC20 deployed has infinite supply deliberately which gives the token no value.

**Mainnet deployment details:**

**Contract	Address:**
Migrations	        0xc7CE6f3B6df2C5f553F3CDBe4Deba1fcD6DfD892
Verifier_Registry	0x3591F96D05B8d2b57262eEa4CF9A1c316598D634
BN256G2	        0x4FfB3281a57a4D922a9A4fc6bf445fbF44F5908a
GM17_v0	                 0xCC6A1Db605D20eFC2D5B1230D2522e06552C6417
NFTokenMetadata	0x24A7226F78e88937Dc0A294b942B420419CCD314
NFTokenShield	0xB1C0Fa5fFD312FDEC7064BBdb14E5a00021446Fe
FToken	                0x8575CC89bd517DA7e8B7c27DC07ab8bE617A90b5
FTokenShield	        0x636b2E5b6d779e4278314D5B127F42713E2e68B9
