### ISSUE TITLE
Validate successful integration on public network with third parties

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#161]
# BLOCKERS

- [ ] #160 Write and perform full integration test against Ropsten network

# Description

The integration test to Ropsten will leave enduring artifacts and will be permanently accessible for third parties.

So let's invite third parties to test it!

Notice from [the README](https://github.com/EYBlockchain/nightfall/blob/master/README.md): 

> Note that this code has not yet completed a security review and therefore we strongly recommend that you do not use it in production or to transfer items of material value. We take no responsibility for any loss you may incur through the use of this code.

---

It is possible that that issue may be satisfied by deploying in a way that is less secure than would be done in a production deployment. For example, the "toxic waste" for this deployment may be published. Such details and a full work scope will be determined and committed BEFORE such work on this issue commences.

#### System information

(Not applicable)

#### Expected behaviour

- [ ] Nightfall is documented and demonstrated to be able to connect to Ropsten network
- [ ] Ensure UI works connected to Ropsten, using only documented process
- [ ] Ensure transactions work with third parties

**Comment by ChaitanyaKonda** [comment]
Closing this issue because nightfall is only currently deployed for demo purposes
