### ISSUE TITLE
Accounts module hardcodes a dependency on ganache host

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#167]
# Description

This files default.json and test.json in the accounts module have a hardcoded hostname http://ganache[_test]:8545". This prevents composition of modules.

#### System information

(Not applicable)

#### Expected behaviour

The configuration should be specified in config.js like the other modules, e.g. zkp/src/config.js.

Or the files should be removed, (I can't see how they are used)...

**Comment by ChaitanyaKonda** [comment]
#147 handles this. Hence closing
