### ISSUE TITLE
Extract all host configurations options to Docker Compose environment variables

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#168]
# BLOCKERS

- [ ] #167 Accounts module hardcodes a dependency on ganache host

# Description

Host names are included inside zkp configuration in config.js. Host names are also configurable through environment variables. For consistency and extensibility, all host name configuration should be through environment variables through Docker Compose.

#### System information

(Not applicable)

#### Expected behaviour

Docker Compose is responsible for rewiring all inter-module connections

**Comment by fulldecent** [comment]
PR COMING

**Comment by ChaitanyaKonda** [comment]
#174 and #172 handle this. Closing
