### ISSUE TITLE
install.sh: Separate `npm install` from `setupAll`

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#189]
# Description
At the moment in `install.sh`, we've bundled `npm ci` commands (for each microservice) with the setupAll command:
```
#!/usr/bin/env bash

# Exit script as soon as a command fails.
set -o errexit

cd zkp-utils && npm ci && \
cd ../account-utils && npm ci && \
cd ../zkp && npm ci && \
npm run setup-all && cd ../
```
As a developer, I want to be able to quickly install stuff, without having to do a zk-SNARK setup.

Can we add a separate `install-dev.sh` script (or some other name) which does not contain the setupAll script? That way if I want to quickly install stuff, I can, with less faff.

**Comment by fulldecent** [comment]
Copying in a related goal:

The trusted setup process takes an hour or so to run and each time you run it you get different results.

Currently, the trusted setup process will permanently overwrite any previous outputs. There are workarounds for this including documentation and the safe-dump folder.

This is unnecessary complexity. Instead, the trusted setup should simply refuse to run if files already exist in the output directory. It should be the responsibility of the end user to delete any files if that is their intent.
