### ISSUE TITLE
fix zkp unit tests

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#190]
# Description

unit tests within zkp appear to be outdated (relative to code changes in this repo) and not running. They'll need updating.

**Comment by iAmMichaelConnor** [comment]
I suggest we update to mocha / truffle tests (rather than jest), because the integration testing uses mocha.
Also, the process for launching a zkp unit-test is a bit convoluted at the moment. It goes through a makefile to a docker-compose script to an npm script.

**Comment by fulldecent** [comment]
Related #78
