### ISSUE TITLE
Point out alternative to Docker-Proxy in the Readme file

### ISSUE THREAD

**Issue by otto-mora** [EYBlockchain/nightfall#20]
Hello,

On the Readme.MD we may want to point to out that there is an alternative to docker-proxy for folks running in Linux. It's called Dory> https://github.com/FreedomBen/dory  we use it in our Ubuntu VMs here in Costa Rica and it seems to be a good replacement. 

Best,

Otto

**Comment by aj-may** [comment]
Would you or the team be willing to test with dory and make a PR to update the readme?

**Comment by ChaitanyaKonda** [comment]
@aj-may I was planning to do it tomorrow. If you prefer to take it up, that sounds good too.

**Comment by otto-mora** [comment]
Hey AJ,
I was going to, but then realized my virtual machine is not strong enough to run Nightfall  :-(

I can safely say however that we use this as a replacement in Dicon for folks running in Linux.

Thanks,

Otto

**Comment by otto-mora** [comment]
One more thing to note, at least in Ubuntu, is that you need to bring the systemd-resolved service back up manually after you bring Dory down. We usually run this command for that:

`sudo service systemd-resolved restart`

**Comment by gabygarro** [comment]
I develop for Dicon in Linux using Dory. Anyone who wants to do this should know that having installed docker-proxy previously may cause some conflicts. I had to reset some network configurations files in my computer before Dory started working.

**Comment by ChaitanyaKonda** [comment]
#16 combined into this issue.

**Comment by Solexplorer** [comment]
@ChaitanyaKonda It's not explained what network configurations had to be changed...

**Comment by aj-may** [comment]
I've been working on a new project to replace `docker-proxy` called `dotdocker`:
https://github.com/aj-may/dotdocker

I've tested it on Ubuntu 18.04 successfully.  I had to run `systemctl stop systemd-resolved` to free up port `53` first.  Once you disable this, you will need to update `/etc/resolv.conf` with an external nameserver(s) like `1.1.1.1`,`8.8.8.8`, and/or `8.8.4.4`.

If anyone feels like giving it a spin, I'd love to get your feedback.

**Comment by outkaj** [comment]
i've just given `dotdocker` a spin on an Ubuntu 18.04 VM on AWS but ran into an error.

my steps - 

make sure `docker-proxy` is stopped by running `docker-proxy stop`
`sudo systemctl stop systemd-resolved`
add 8.8.8.8 to `/etc/resolv.conf`
`sudo npm install -g dotdocker`
`sudo dotdocker start`

output:

```
sudo: unable to resolve host ip-*machine-ip*
  ❯ Start dotdocker containers
    ❯ Start proxy
      ⠏ Pulling codekitchen/dinghy-http-proxy:latest
        → 4c394a654280: Download complete
        Creating dotdocker-proxy
        Starting dotdocker-proxy
    ❯ Start dnsmasq
      ✔ Pulling andyshinn/dnsmasq:latest
      ✔ Creating dotdocker-dnsmasq
      ✖ Starting dotdocker-dnsmasq
        → (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (697c21fa66b20918b27c81da376
…
    Setting up DNS
(node:8818) UnhandledPromiseRejectionWarning: Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (697c21fa66b20918b27c81da3761a7a38055af0ae7705d0c826afa9c35d883c5): Error starting userland proxy:  
    at /usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ocgordon** [comment]
> i've just given `dotdocker` a spin on an Ubuntu 18.04 VM on AWS but ran into an error.
> 
> my steps -
> 
> make sure `docker-proxy` is stopped by running `docker-proxy stop`
> `sudo systemctl stop systemd-resolved` (note - if I restart this before running `dotdocker` I get the same error)
> add 8.8.8.8 to `/etc/resolv.conf`
> `sudo npm install -g dotdocker`
> kill any processes on ports 53, 80, 443
> `sudo dotdocker start`
> 
> output:
> 
> ```
> sudo: unable to resolve host ip-*machine-ip*
>   ❯ Start dotdocker containers
>     ❯ Start proxy
>       ⠏ Pulling codekitchen/dinghy-http-proxy:latest
>         → 4c394a654280: Download complete
>         Creating dotdocker-proxy
>         Starting dotdocker-proxy
>     ❯ Start dnsmasq
>       ✔ Pulling andyshinn/dnsmasq:latest
>       ✔ Creating dotdocker-dnsmasq
>       ✖ Starting dotdocker-dnsmasq
>         → (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (697c21fa66b20918b27c81da376
> …
>     Setting up DNS
> (node:8818) UnhandledPromiseRejectionWarning: Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint dotdocker-dnsmasq (697c21fa66b20918b27c81da3761a7a38055af0ae7705d0c826afa9c35d883c5): Error starting userland proxy:  
>     at /usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:257:17
>     at getCause (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:287:7)
>     at Modem.buildPayload (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:256:5)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/dotdocker/node_modules/docker-modem/lib/modem.js:232:14)
>     at IncomingMessage.emit (events.js:203:15)
>     at endReadableNT (_stream_readable.js:1129:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:8818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:8818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

**Comment by outkaj** [comment]
cc @aj-may re: my comment above and let me know if I should move that as an issue in dot-docker repo (wasn't sure exactly where to put it, since it has to do with intersection of dot-docker & nightfall, it seems)

**Comment by aj-may** [comment]
@outkaj Feel free to open an issue on `dotdocker`.  Usually that error is caused by another service already listening on port `53` or docker not having permissions to listen on that port.

**Comment by ocgordon** [comment]
Readme is updated to `dot-docker`
