### ISSUE TITLE
Fix or consolidate docker-compose.test.yml

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#205]
# Description
I believe the intention for these two separate docker-compose files was to enable people to run both the proper application and the test environment simultaneously.

However, when docker-proxy was removed from the repo, it has resulted in port collisions between these two docker-compose files. Therefore both of these docker-compose files appear to serve the exact same purpose and therefore feel like unnecessary duplication.

Do we want users to be able to test at the same time as having the nightfall application whirring in the background? If so, we need to change the ports of the docker-compose.test containers. I think this adds a bit too much complexity.

Alternative: remove all of the docker-compose.test.yml functionality and allow testing within the default set of containers in docker-compose.yml (my preferred choice).

**Comment by fulldecent** [comment]
I agree that this is best:

> remove all of the docker-compose.test.yml functionality and allow testing within the default set of containers in docker-compose.yml (my preferred choice).

I have an issue coming later about project organization later. But more immediately I believe the goals here are:

1. Module-level documentation (#119)
2. Module-level testing
3. Integration testing

I think these largely obviate the need for the test compose file.
