### ISSUE TITLE
Create a universal FTokenShield contract to shield multiple ERC-20 tokens

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#237]
# Description

Currently the FTokenShield 'shield contract' can only point to a single ERC-20 contract. A new shield contract must be deployed for each token.

Suggested steps for this Issue:
- Update FTokenShield.sol to handle any and all ERC-20 contracts. (I.e. allow deposits and withdrawals (mints & burns) from and to any ERC-20 contract).
- Update the relevant database schemas to handle this extra functionality.
- Update the ZoKrates proofs (`.code` files) to inextricably link the address of a particular ERC-20 contract to the commitments and proofs.
- Update node.js logic to handle the above.

**Comment by Westlad** [comment]
This functionality now available in Nightlite.
