### ISSUE TITLE
Not able to create an account

### ISSUE THREAD

**Issue by Nayyar525** [EYBlockchain/nightfall#243]
Please find the below details 

This is continue to the issue #66  created by @bansatya

**System information**

Docker version: `docker version` 
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

OS & Version: **Linux**
Commit hash : (if `develop`)

#### Expected behaviour
**Account should be created** 
#### Actual behaviour
**Error is coming while account is created

error message {"error":{"code":253,"message":"Command failed: mongo nightfall --host=mongo -u admin -p admin setup-mongo-acl-for-new-users.js\n"},"data":null}**

#### Steps to reproduce the behaviour
login--> Create account--> error
#### Backtrace

````
[backtrace]
````

#### Logs

mongo_1             | 2019-10-14T12:23:09.767+0000 I  NETWORK  [conn7] end connection 192.168.112.11:43454 (5 connections now open)
database_1          | error: POST:/users
database_1          |     {"error":"Command failed: mongo nightfall --host=mongo -u admin -p admin setup-mongo-acl-for-new-users.js\n"}
database_1          |     {
database_1          |  "errorStack": [
database_1          |   "Error: Command failed: mongo nightfall --host=mongo -u admin -p admin setup-mongo-acl-for-new-users.js",
database_1          |   "",
database_1          |   "    at ChildProcess.exithandler (child_process.js:299:12)",
database_1          |   "    at ChildProcess.emit (events.js:193:13)",
database_1          |   "    at maybeClose (internal/child_process.js:999:16)",
database_1          |   "    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)"
database_1          |  ]
database_1          | }
database_1          |     {"body":{"name":"gaurav","email":"nayyar525@gmail.com","password":"12345","address":"0xedb9460159Af82eB2Ff10A5291a9C8e059c9d868","shhIdentity":""}}
database_1          |     {"params":{}}
database_1          |     {"query":{}}
database_1          |
mongo_1             | 2019-10-14T12:23:09.772+0000 I  COMMAND  [conn3] command nightfall.gaurav_ft_commitment_transactions command: createIndexes { createIndexes: "gaurav_ft_commitment_transactions", indexes: [ { name: "coin_commitment_1", key: { coin_commitment: 1 }, background: true } ], lsid: { id: UUID("a693a82c-975f-4dcd-94dc-758579d10741") }, $db: "nightfall" } numYields:0 reslen:114 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 2 } }, ReplicationStateTransition: { acquireCount: { w: 3 } }, Global: { acquireCount: { r: 1, w: 2 } }, Database: { acquireCount: { r: 1, w: 2 } }, Collection: { acquireCount: { r: 4, w: 1, R: 1, W: 2 } }, Mutex: { acquireCount: { r: 4 } } } flowControl:{ acquireCount: 1 } storage:{} protocol:op_msg 359ms
database_1          | [object Object]
api-gateway_1       | { code: 253,
api-gateway_1       |   message:
api-gateway_1       |    'Command failed: mongo nightfall --host=mongo -u admin -p admin setup-mongo-acl-for-new-users.js\n',
api-gateway_1       |   errorStack:
api-gateway_1       |    'Error: Command failed: mongo nightfall --host=mongo -u admin -p admin setup-mongo-acl-for-new-users.js\n\n    at ChildProcess.exithandler (child_process.js:299:12)\n    at ChildProcess.emit (events.js:193:13)\n    at maybeClose (internal/child_process.js:999:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)' }
api-gateway_1       | [object Object]
mongo_1             | 2019-10-14T12:23:09.782+0000 I  INDEX    [conn4] index build: done building index token_shield_contracts.contract_address_1 on ns nightfall.gaurav_users
mongo_1             | 2019-10-14T12:23:09.801+0000 I  INDEX    [conn1] index build: done building index shield_contract_address_1 on ns nightfall.gaurav_ft_transactions
mongo_1             | 2019-10-14T12:23:09.809+0000 I  COMMAND  [conn2] command nightfall.gaurav_ft_commitments command: createIndexes { createIndexes: "gaurav_ft_commitments", indexes: [ { name: "coin_commitment_1", key: { coin_commitment: 1 }, unique: true, background: true } ], lsid: { id: UUID("8cc1d308-31e2-4702-9763-79e5815d5144") }, $db: "nightfall" } numYields:0 reslen:114 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 2 } }, ReplicationStateTransition: { acquireCount: { w: 3 } }, Global: { acquireCount: { r: 1, w: 2 } }, Database: { acquireCount: { r: 1, w: 2 } }, Collection: { acquireCount: { r: 4, w: 1, R: 1, W: 2 } }, Mutex: { acquireCount: { r: 4 } } } flowControl:{ acquireCount: 1 } storage:{} protocol:op_msg 416ms
mongo_1             | 2019-10-14T12:23:09.811+0000 I  COMMAND  [conn1] command nightfall.gaurav_ft_transactions command: createIndexes { createIndexes: "gaurav_ft_transactions", indexes: [ { name: "shield_contract_address_1", key: { shield_contract_address: 1 }, background: true } ], lsid: { id: UUID("b767cf7a-1d2f-4413-84fa-fe95b8e52d68") }, $db: "nightfall" } numYields:0 reslen:114 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 2 } }, ReplicationStateTransition: { acquireCount: { w: 3 } }, Global: { acquireCount: { r: 1, w: 2 } }, Database: { acquireCount: { r: 1, w: 2 } }, Collection: { acquireCount: { r: 4, w: 1, R: 1, W: 2 } }, Mutex: { acquireCount: { r: 4 } } } flowControl:{ acquireCount: 1 } storage:{} protocol:op_msg 342ms
mongo_1             | 2019-10-14T12:23:09.820+0000 I  COMMAND  [conn4] command nightfall.gaurav_users command: createIndexes { createIndexes: "gaurav_users", indexes: [ { name: "token_shield_contracts.contract_address_1", key: { token_shield_contracts.contract_address: 1 }, unique: true, background: true } ], lsid: { id: UUID("c3a3395a-800d-482d-9b64-8bb0a8fcec58") }, $db: "nightfall" } numYields:0 reslen:114 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 2 } }, ReplicationStateTransition: { acquireCount: { w: 3 } }, Global: { acquireCount: { r: 1, w: 2 } }, Database: { acquireCount: { r: 1, w: 2 } }, Collection: { acquireCount: { r: 2, w: 1, R: 1, W: 2 } }, Mutex: { acquireCount: { r: 4 } } } flowControl:{ acquireCount: 1 } storage:{} protocol:op_msg 348ms

**Comment by Nayyar525** [comment]
**update**

When i tired the same to create an account i got this particular message in console

{"error":{"code":51003,"message":"User \"gaurav@nightfall\" already exists"},"data":null} 

Please look into this

**Comment by cyberbono3** [comment]
I have encountered the similar issue. Although i have successfully created account I was not able to log in. I am using Ubuntu as well.
`ganache_1         | eth_subscribe
database_1          | error: POST:/db-connection
database_1          |     {"error":"Unescaped at-sign in authority section"}
database_1          |     {
database_1          |  "errorStack": [
database_1          |   "MongoParseError: Unescaped at-sign in authority section",
database_1          |   "    at parseConnectionString (/app/node_modules/mongodb-core/lib/uri_parser.js:538:21)",
database_1          |   "    at connect (/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:195:3)",
database_1          |   "    at connectOp (/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)",
database_1          |   "    at executeOperation (/app/node_modules/mongodb/lib/utils.js:416:24)",
database_1          |   "    at MongoClient.connect (/app/node_modules/mongodb/lib/mongo_client.js:175:10)",
database_1          |   "    at Promise (/app/node_modules/mongoose/lib/connection.js:558:12)",
database_1          |   "    at new Promise (<anonymous>)",
database_1          |   "    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:555:19)",
database_1          |   "    at Mongoose.createConnection (/app/node_modules/mongoose/lib/index.js:244:17)",
database_1          |   "    at Function.createConnection [as setDBconnection] (/app/src/business/user.service.js:86:44)",
database_1          |   "    at setDBconnection (/app/src/routes/user.routes.js:16:42)",
database_1          |   "    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)",
database_1          |   "    at next (/app/node_modules/express/lib/router/route.js:137:13)",
database_1          |   "    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)",
database_1          |   "    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)",
database_1          |   "    at /app/node_modules/express/lib/router/index.js:281:22"
database_1          |  ]
database_1          | }
database_1          |     {"body":{"name":"cyberbono3@gmail.com","password":"qwerty"}}
database_1          |     {"params":{}}
database_1          |     {"query":{}}
database_1          |   
database_1          | [object Object]
api-gateway_1       | [object Object]
database_1          | error: POST:/db-connection
database_1          |     {"error":"Unescaped at-sign in authority section"}
database_1          |     {
database_1          |  "errorStack": [
database_1          |   "MongoParseError: Unescaped at-sign in authority section",
database_1          |   "    at parseConnectionString (/app/node_modules/mongodb-core/lib/uri_parser.js:538:21)",
database_1          |   "    at connect (/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:195:3)",
database_1          |   "    at connectOp (/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)",
database_1          |   "    at executeOperation (/app/node_modules/mongodb/lib/utils.js:416:24)",
database_1          |   "    at MongoClient.connect (/app/node_modules/mongodb/lib/mongo_client.js:175:10)",
database_1          |   "    at Promise (/app/node_modules/mongoose/lib/connection.js:558:12)",
database_1          |   "    at new Promise (<anonymous>)",
database_1          |   "    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:555:19)",
database_1          |   "    at Mongoose.createConnection (/app/node_modules/mongoose/lib/index.js:244:17)",
database_1          |   "    at Function.createConnection [as setDBconnection] (/app/src/business/user.service.js:86:44)",
database_1          |   "    at setDBconnection (/app/src/routes/user.routes.js:16:42)",
database_1          |   "    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)",
database_1          |   "    at next (/app/node_modules/express/lib/router/route.js:137:13)",
database_1          |   "    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)",
database_1          |   "    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)",
database_1          |   "    at /app/node_modules/express/lib/router/index.js:281:22"
database_1          |  ]
database_1          | }
database_1          |     {"body":{"name":"cyberbono3@gmail.com","password":"qwerty"}}
database_1          |     {"params":{}}
database_1          |     {"query":{}}
database_1          |   
database_1          | [object Object]
api-gateway_1       | [object Object]`

**Comment by vishnusudarshan** [comment]
Hi @Nayyar525, @cyberbono3

@Nayyar525, from the provided logs, create account process failed midway. It did created user in db and failed to configure user ACL in mongo, which this error message says:
```
error message {"error":{"code":253,"message":"Command failed: mongo nightfall --host=mongo -u admin -p admin setup-mongo-acl-for-new-users.js\n"},"data":null}
```

Thus, below error message is as expected (as user exist in the dB)
```
{"error":{"code":51003,"message":"User "gaurav@nightfall" already exists"},"data":null}
@Nayyar525 and @cyberbono3
```

Can you also share what was the user input to these failed create account?
Note: While creating an account - user name must unique, lowercase, and without special characters and spaces

**Comment by cyberbono3** [comment]
@vishnusudarshan  Although I have successfully created an account using Ubuntu but was not be able to login.
The login credentials were aivasko@mail.ru  qwerty 
You can find error details  [here](https://play.golang.org/p/KSazvuZCN7V)

**Comment by vishnusudarshan** [comment]
@cyberbono3 : You can try login with username and password instead of email and password.

**Comment by cyberbono3** [comment]
@vishnusudarshan Thanks for your advice.  I have successfully logged in with username

**Comment by Westlad** [comment]
Closed as no further input.
