### ISSUE TITLE
Compute proof generation and verification times for BLS12_377, SW6, MNT4753 and MNT6753

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall#254]
#Description 

Computing proof generation and verification times for these curves to understand which approach to go forward with for now

- BLS12_377 for inner curve with SW6 for outer curve (non-recursive approach)
- MNT4753 - MNT6753 (recursive approach)

**Comment by Westlad** [comment]
Closed because completed

**Comment by ChaitanyaKonda** [comment]
Considering that [EIP-1961](https://eips.ethereum.org/EIPS/eip-1962) doesn't provide an estimation of gas costs, calculating verification costs on chain by assuming time taken as a naive way to approximately estimate.

Generate Proof (a factor of -- compared to ALT_BN128)
BLS12 : 1.17 - 1.25
SW6 : 2.54 - 2.64
MNT4753 : 3.65 - 4.34
MNT6753 : 3.38 - 5.33

Verify Proof (a factor of -- compared to ALT_BN128)
BLS12 : 1.05 - 1.25
SW6 : 10.07 - 10.52
MNT4753 : 4.02 - 4.31
MNT6753 : 7.29 - 7.59

*All processes run on 32GB RAM with 8 vCPUs.

Verifying on MNT4753 is cheaper than verifying on SW6.
By a factor of more than 2.
Recursiveness being a huge benefit on top of that. 

This and other analyses led to the decision of batching with MNT4753 and MNT6753.
