### ISSUE TITLE
Ganache Issue

### ISSUE THREAD

**Issue by walter-grace** [EYBlockchain/nightfall#28]
I am getting the following error when trying to run ./zkp-demo,
anyone else run into this issue? 

*** Launching containerized ganache ***
Creating network "nightfall_default" with the default driver
Creating volume "nightfall_mongo-volume" with default driver
Creating volume "nightfall_zkp-code" with local driver
Creating nightfall_ganache_1 ... error

ERROR: for nightfall_ganache_1  Cannot start service ganache: driver failed programming external connectivity on endpoint nightfall_ganache_1 (fc67274f540400c7a2deca2785d5aeb0a963309da017a80bda9ebc2e38597401): Bind for 0.0.0.0:8545 failed: port is already allocated

**Comment by asishap** [comment]
Hi @walter-grace ,
As per the error some other services is already using port `8545`. Could you remove all running docker containers ?  Following commands would helps you
```
#To stop all Nightfall related containers
docker-compose down -v
# To kill all running containers
docker kill $(docker ps -q)
# Delete all containers
docker rm $(docker ps -a -q)
```
Then you can try to run the ./zkp-demo script again.

**Comment by Westlad** [comment]
also lsof -i :8545 will tell you if some other process has grabbed the port.  Then you can kill it.

**Comment by walter-grace** [comment]
Thanks for that help!
The ganache part seems to be fixed now, but now this error keeps showing up. 
_ERROR: failed to register layer: sync /var/lib/docker/image/overlay2/layerdb/tmp/write-set-291313389/size: input/output error
make: *** [truffle-migrate] Error 1_

**Comment by asishap** [comment]
@walter-grace 
Could you please  provide the exact steps and commands you have ran ?
Also please paste the entire console log over here.

**Comment by walter-grace** [comment]
**I uninstalled everything and tried again. I am having no problem with the first part now
cd zkp-utils
npm ci
Everything goes smoothly.**

This is where things seem to be going wrong
__cd ../zkp
npm ci_
when I try to do npm ci in the zkp folder this error keeps showing up:
 Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/waltgrace/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/waltgrace/.nvm/versions/node/v12.4.0/bin/node" "/Users/waltgrace/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/waltgrace/Desktop/nightfall-master/zkp/node_modules/scrypt
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waltgrace/.npm/_logs/2019-06-09T00_19_38_894Z-debug.log_

This is where I stopped, not sure what is wrong on my end. I hope this more information helps.

**Comment by mkinney** [comment]
Check your node version. It cannot be 12. It must be 10.

The README.md has been update to reflect this.

To check the node version, run `node --version`
If using mac/brew, then you may need to run `brew install node@10` and `brew link --overwrite node@10 --force`

**Comment by walter-grace** [comment]
Great! Thank you all for the help. Closing this issue.

**Comment by Solexplorer** [comment]
@walter-grace Were you using linux to run NightFall and did it work for you ?

**Comment by walter-grace** [comment]
> @walter-grace Were you using linux to run NightFall and did it work for you ?

I am actually using macOS Mojave; I was having npm permission issues the whole time. But I get nightfall up running, minting EY, transferring and burning tokens.

**Comment by outkaj** [comment]
I'm getting the following error running ganache (on an AWS Ubuntu machine):

```
ERROR: for nightfall_ganache_1  Cannot start service ganache: driver failed programming external connectivity on endpoint nightfall_ganache_1 (cd14b6eb1415a5810e60d8ec360fb1743568bcfe09f129603551609f9ad3d026): Error starting userland proxy: 

ERROR: for ganache  Cannot start service ganache: driver failed programming external connectivity on endpoint nightfall_ganache_1 (cd14b6eb1415a5810e60d8ec360fb1743568bcfe09f129603551609f9ad3d026): Error starting userland proxy: 
ERROR: Encountered errors while bringing up the project.
```

**Comment by mkinney** [comment]
The docker-proxy solution does not work on Ubuntu. @aj-may is trying to see if we can use something else. Tried using dotproxy, and it *almost* works. All builds, but the docker instances just do not see themselves. So, when you try to create a user thru the UI, the UI errors.

**Comment by outkaj** [comment]
@mkinney thanks for clarifying!

are there other Linux distros which it does work on?

**Comment by mkinney** [comment]
I don't know. I have only tried parts on Centos and Ubuntu.

@Westlad or @iAmMichaelConnor : Anyone got Nightfall working on any linux distros?

**Comment by walter-grace** [comment]
Yeah I am trying to figure out a way around the 'docker-proxy start' for anything besides Mac.
 I tried using Windows 10 and ran into these issues as well.

**Comment by outkaj** [comment]
do you mind if I reopen and rename this issue to "Add Linux and Windows support"?

**Comment by walter-grace** [comment]
@outkaj I think that would be a good idea; if the others agree too @mkinney

**Comment by mkinney** [comment]
@walter-grace Yes, I think that makes sense. Please make two different issues: one for windows and one for linux.

**Comment by walter-grace** [comment]
> do you mind if I reopen and rename this issue to "Add Linux and Windows support"?

@outkaj you can open up the Linux Issues
