### ISSUE TITLE
ZKP tests failing

### ISSUE THREAD

**Issue by cmhumer** [EYBlockchain/nightfall#281]
I am trying to run `make zkp-test` while on the latest master branch and 21 out of the 30 tests are failing. These tests should be passing. 
<img width="1038" alt="Screen Shot 2019-10-30 at 3 45 58 PM" src="https://user-images.githubusercontent.com/29980813/67893163-774a4680-fb2c-11e9-988e-3feb594c0b40.png">

Some of the failed tests:

`nf-token-controller.js tests › Should burn the ERC 721 commitment for Bob for asset Z_B_A to return A ERC-721 Token

    Invalid address passed to Contract.at(): undefined

      376 |   const nfTokenShield = contract(nfTokenShieldJson);
      377 |   nfTokenShield.setProvider(Web3.connect());
    > 378 |   const nfTokenShieldInstance = await nfTokenShield.at(nfTokenShieldAddress);
          |                                                     ^
      379 |
      380 |   console.log('Finding the relevant Shield and Verifier contracts');
      381 |   const verifier = await Verifier.at(await nfTokenShieldInstance.getVerifier.call());

      at node_modules/truffle-contract/lib/contract/constructorMethods.js:82:18
      at Function.at (node_modules/truffle-contract/lib/contract/constructorMethods.js:71:14)
      at Object.at [as transfer] (src/nf-token-controller.js:378:53)
      at Object.transfer (__tests__/nf-token-controller.test.js:141:51)

  nf-token-controller.js tests › Should burn the ERC 721 commitment for Bob for asset Z_B_A to return A ERC-721 Token

    Invalid address passed to Contract.at(): undefined

      551 |   const nfTokenShield = contract(nfTokenShieldJson);
      552 |   nfTokenShield.setProvider(Web3.connect());
    > 553 |   const nfTokenShieldInstance = await nfTokenShield.at(nfTokenShieldAddress);
          |                                                     ^
      554 |
      555 |   const payToOrDefault = payTo || account; // have the option to pay out to another address
      556 |   console.group('\nIN BURN...');

      at node_modules/truffle-contract/lib/contract/constructorMethods.js:82:18
      at Function.at (node_modules/truffle-contract/lib/contract/constructorMethods.js:71:14)
      at Object.at [as burn] (src/nf-token-controller.js:553:53)
      at Object.burn (__tests__/nf-token-controller.test.js:160:45)`

**Comment by Westlad** [comment]
There is currently an un-awaited promise issue with the zkp unit tests.  A fix should be pushed soon, which hopefully will resolve this.

**Comment by Westlad** [comment]
Closing as fix has been pushed.  Please re-open if there are still issues.
