### ISSUE TITLE
Implement Groth16 verifier contract, with `Verifier_Interface`

### ISSUE THREAD

**Issue by PossiblyHarry** [EYBlockchain/nightfall#289]
To support verification of Groth16 proofs we need to implement a verifier, and make it easier to switch between GM17 and Groth16 (or other proving systems). There are several places where GM17 is hard-coded.

As per:

 * https://github.com/EYBlockchain/nightfall/blob/master/zkp/contracts/Verifier_Interface.sol

Implement Groth16 zkSNARK verifier, code can be taken from:

 * https://github.com/HarryR/ethsnarks/blob/master/contracts/Verifier.sol

Does not depend on the Pairing or Points library, is standalone. The `NegateY` and `ScalarField` functions can be removed, the verification key and proof will need to be preprocessed before passing to the contract.

The GM17 library is used in the following places:

 * https://github.com/EYBlockchain/nightfall/blob/183f3b346e2cec8c0c438a4187c14241499e9a36/zkp/migrations/2_Shield_migration.js#L3
 * https://github.com/EYBlockchain/nightfall/blob/183f3b346e2cec8c0c438a4187c14241499e9a36/zkp/migrations/2_Shield_migration.js#L17
 * https://github.com/EYBlockchain/nightfall/blob/379502b29e64e7fc5458c6e37e94f9935ffdde80/zkp/src/contractUtils.js#L13
 * https://github.com/EYBlockchain/nightfall/blob/3bfccac379554fc94dac060851347d6b5ebdd35d/zkp/src/vk-controller.js#L28
 * https://github.com/EYBlockchain/nightfall/blob/f90bb0bbd22e99570fa635669ee5dfe32b78949c/zkp/src/f-token-controller.js#L30
 * https://github.com/EYBlockchain/nightfall/blob/f90bb0bbd22e99570fa635669ee5dfe32b78949c/zkp/src/nf-token-controller.js#L31

The references in vk-controller.js, f-token-controller.js and nf-token-controller.js can use the `Verifier` attribute from `contractUtils.js` rather than hard-coding `GM17_v0`.

The `verifier` and `verifierRegistry` variables don't seem to be used in `f-token-controller.js` or `nf-token-controller.js`

**Comment by Westlad** [comment]
Now intending to use Zexe and BW6.
