### ISSUE TITLE
Sample transaction IDs onchain?

### ISSUE THREAD

**Issue by 1blockologist** [EYBlockchain/nightfall#3]
Hello, a fan of the work and have been following ZKPs for most of the decade, can you post example transactions onchain for easy inspection? with a way if possible to prove the balance to support the example or what a user can expect to get out of it?

Such quick inspection would allow many of us to decide if this is something worth compiling and playing around with, or easily seeing if this is a solution for something they have in mind, especially with the specific resource requirements needed.

**Comment by Chaitanya-Konda** [comment]
That indeed would be helpful and nice that you brought it up.
We in fact did exactly just that back in October of 2018. 
Performed transactions using Nightfall protocol on main net and released a challenge to break it. 
[The repo](https://github.com/EYBlockchain/ZKPChallenge.)

**Comment by 1blockologist** [comment]
Oh thank you!

I had been trying to reach spokespeople like Paul Brody on the EY Ops Chain projects about simple sample transactions for months, following every press release. 

Where would I have known about this? I think there are other people like me that don't know how to contact anyone at EY

**Comment by Chaitanya-Konda** [comment]
Good to hear that. 
At EY, we are very public about the work we do. 
The ZKPChallenge as well as Nightfall have been covered by multiple news organisations.

**Comment by 1blockologist** [comment]
The ZKPChallenge repository mentions patent pending

Can you clarify how that works with having this project mentioned to be the public domain to the extent possible?

A more familiar license like MIT or Apache would be more helpful than just saying public domain

**Comment by Chaitanya-Konda** [comment]
The documentation in ZKPChallenge will be updated to reflect that Nightfall is public domain.

**Comment by prbrody** [comment]
> Oh thank you!
> 
> I had been trying to reach spokespeople like Paul Brody on the EY Ops Chain projects about simple sample transactions for months, following every press release (which was devoid of sample transactions or clear ways to learn more).
> 
> Where would I have known about this? I think there are other people like me that don't know how to contact anyone at EY when cold contacting fails

With apologies or not being able to reply, I’m challenged on email and linked in - I just can’t keep up.
