### ISSUE TITLE
Burning of EY Opscoin commitment not working

### ISSUE THREAD

**Issue by EleonoraMuller** [EYBlockchain/nightfall#30]
After successfully transferring an EY OpsCoin Commitment from user a to b, I tried to burn the coin that user b had gotten by pressing the Burn EY OpsCoin Commitment button and it gave me an error and never burned it (see attached screenshot).

<img width="1378" alt="Screen Shot 2019-06-07 at 17 05 08" src="https://user-images.githubusercontent.com/49447246/59117739-71b64f00-8946-11e9-8a17-5e7f6c5dd148.png">

**Comment by ChaitanyaKonda** [comment]
@EleonoraMuller Can you provide more log information that is above the current log screenshot? 

Without complete log information, from a quick look, it seems Verifying keys for Burn could be missing. You could check if that is the case by looking into vkIds.json. If so, then your trusted-setup for burn might have failed. In which case you can run,`npm run setup -- -i gm17/ft-burn/` from root directory

**Comment by jwhelan72** [comment]
I can confirm this error.  It appears intermittently though.

![image](https://user-images.githubusercontent.com/1807284/59161996-f392ad80-8ae9-11e9-9f47-629aac8092cb.png)

**Comment by mkinney** [comment]
@jwhelan72 Can you run this command: `ls -al ./zkp/code/gm17/ft-burn/ft-burn*`?

For me, it shows these three files:

```
$ ls -al ./zkp/code/gm17/ft-burn/ft-burn*
-rw-r--r--  1 mikekinney  staff    2475 Jun  9 17:31 ./zkp/code/gm17/ft-burn/ft-burn-vk.json
-rw-r--r--  1 mikekinney  staff  727993 Jun  9 17:27 ./zkp/code/gm17/ft-burn/ft-burn.code
-rw-r--r--  1 mikekinney  staff    4241 Jun  7 11:50 ./zkp/code/gm17/ft-burn/ft-burn.pcode
```

I was able to do these steps successfully:
1) mint EY Opscoin
2) mint EY Opscoin Commitment
3) transfer EY Opscoin Commitment from a to b
4) login as b
5) Burn EY Opscoin Commitment
6) Burn EY Opscoin

Do those look like the same steps you took?

**Comment by mkinney** [comment]
Oops. I meant to direct that comment above to @EleonoraMuller

**Comment by EleonoraMuller** [comment]
I tried to burn the EY OpsCoin Commitment again, twice, and the error didn't occur again.
