### ISSUE TITLE
Switch to Node 10 or 12

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#305]
# Description

Currently the project is using Node 11. This version is not supported by the vendor. We should switch to supported version 10 or 12.

#### System information

Not relevant

#### Discussion

Vendor support schedule is at https://github.com/nodejs/Release

Version 11 is not listed and therefore is not supported. (I tried to get that project to list version 11 there and say not supported to be more clear, but they don't want to.)

**Comment by vishnusudarshan** [comment]
Closing the issue hence we can’t currently use node 12 with Truffle. In the meantime, we can use node v11 and update it to node v12 when it supports.
