### ISSUE TITLE
Adopt Standard JS

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#306]
# Description

Standard JS is a more opinionated linter.

Thank you to Kevin Clough at Jarvus for contributing this suggestion.

#### System information

Not applicable

#### Expected behaviour

Implement Standard JS linting at https://github.com/EYBlockchain/nightfall/blob/master/.eslintrc.js or as a separate linting step.

#### Actual behaviour

Only eslint is used.

**Comment by ChaitanyaKonda** [comment]
We are working with Airbnb listing standards across EYBlockchain repositories
