### ISSUE TITLE
no such file or directory, open '/app/code/gm17/ft-mint/proof.json

### ISSUE THREAD

**Issue by DoubleCherish** [EYBlockchain/nightfall#308]
Compute-witness...
zkp_1               |     ./zokrates compute-witness -a 76249808349968896065515824549909926450617149809843230170361858589453424324 3 221420994192278153749482905570825000096 207998405846370223830125233444174264027 189092191092984424540861335177295778603 7130756871984606870143145958977578293 301979694280191356883642214663975604958 266630950579047070676911377958342267186 -i code/gm17/ft-mint/out
zkp_1               |     (you can paste the above line into the container to debug the 'compute-witness' step)
zkp_1               |     
zkp_1               |     Generating Proof := P(pk,w,x)
zkp_1               |     Backend being used gm17
zkp_1               |     POST:/mintFTCommitment
zkp_1               |         {"error":"/app/code/gm17/ft-mint/proof.json: ENOENT: 

- [ ] 

1. no such file or directory, open '/app/code/gm17/ft-mint/proof.json

'"}
zkp_1               |         {
zkp_1               |      "errorStack": [
zkp_1               |       "Error: /app/code/gm17/ft-mint/proof.json: ENOENT: no such file or directory, open '/app/code/gm17/ft-mint/proof.json'",
zkp_1               |       "    at Object.openSync (fs.js:448:3)",
zkp_1               |       "    at Object.readFileSync (fs.js:348:35)",
zkp_1               |       "    at readFileSync (/app/node_modules/jsonfile/index.js:61:22)",
zkp_1               |       "    at Object.generateProof (/app/src/zokrates.js:201:21)",
zkp_1               |       "    at processTicksAndRejections (internal/process/task_queues.js:86:5)"
zkp_1               |      ]
zkp_1               |     }
zkp_1               |         {"body":{"amount":"0x00000000000000000000000000000003","ownerPublicKey":"0xa69421de9d8506c74d2b33710448d4a09c7b092b8725c644e1d28839af9976db"}}
zkp_1               |         {"params":{}}
zkp_1               |         {"query":{}}
zkp_1               |       
zkp_1               |     {
zkp_1               |       "errno": -2,
zkp_1               |       "syscall": "open",
zkp_1               |       "code": "ENOENT",
zkp_1               |       "path": "/app/code/gm17/ft-mint/proof.json"
zkp_1               |     }
zkp_1               |     [object Object]

**Comment by Westlad** [comment]
The usual cause of this sort of error is that the proving system is incompatible with the node code.  This can happen if you've recently pulled the code but haven't updated the proofs for a while.  If that could be the case then run `npm run setupAll` and `docker-compose build` again.

**Comment by Westlad** [comment]
It's also possible that you don't have enough memory allocated to your docker containers.  This is very important and the default is not sufficient.  Check the readme if you think that could be the case.

**Comment by DoubleCherish** [comment]
> It's also possible that you don't have enough memory allocated to your docker containers. This is very important and the default is not sufficient. Check the readme if you think that could be the case.

my linux system memory is 10g and  swap is 4g

**Comment by DoubleCherish** [comment]
@Westlad Do you have any suggestions ?

**Comment by Westlad** [comment]
Hi @DoubleCherish can you confirm that you have allocated all of that 10GB+4GB for the docker containers to use.  Docker isn't normally configured to use every scrap of system memory by default (although it depends on your system).  Additionally did you do the setupAll and build again as above and did that make any difference?

**Comment by Westlad** [comment]
Closing as no further input, therefore assuming issue is resolved.  Please reopen if this is not the case.
