### ISSUE TITLE
First transfer of OpsCoin never appears in B's wallet

### ISSUE THREAD

**Issue by jwhelan72** [EYBlockchain/nightfall#31]
1. I set up two users A & B
2. Mint 100 EY OpsCoin
3. Commit 10
4. Commit 20
5. Transfer 15 shielded OpsCoin from A to B

![image](https://user-images.githubusercontent.com/1807284/59152971-b679dd00-8a4f-11e9-9205-b5ae20335f5d.png)

6. Coins leave A but do not appear in B

![image](https://user-images.githubusercontent.com/1807284/59152980-db6e5000-8a4f-11e9-8918-c52c7d14a950.png)

7. This problem only appears to happen for the very first transfer.  Transfers after that seem to appear just fine.

**Comment by ChaitanyaKonda** [comment]
@jwhelan72 This doesn't appear to happen in any of our tests. 

Can you try a few things?

- Try using two different browsers ? Or the same browser with one in normal mode and another in incognito ? 
- Log out and log into B when it doesn't appear the first time?

**Comment by jwhelan72** [comment]
Checking this.  I was using a single Chrome instance in normal mode and logging in and out each time.  I will check against Chrome & Safari.

**Comment by jwhelan72** [comment]
Seems to work fine across two different browsers - Chrome & Safari.
