### ISSUE TITLE
Trusted Setup Failing

### ISSUE THREAD

**Issue by Genysys** [EYBlockchain/nightfall#334]
# Description

I am unable to generate constraints when i run the trusted set up

#### System information

OS: MacOS Mojave
Truffle v5.0.19 (core: 5.0.19)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
Docker version 19.03.1, build 74b1e89

#### Expected behaviour

- Command: `npm run setupAll`
- Result: Set up completed

#### Actual behaviour

- Command: `npm run setupAll`
- Result: Set up fail

#### Steps to reproduce the behaviour

- git clone --recurse-submodules git@github.com:EYBlockchain/nightfall.git
- cd nightfall
- docker pull zokrates/zokrates:0.5.1
- npm run setupAl

#### Backtrace

````
[backtrace]
````

#### Logs

     (1 * ~one) * (1 * _3016228) == 1 * _429
        (1 * ~one) * (1 * _3016227) == 1 * _430
        (1 * ~one) * (1 * _3016226) == 1 * _431
        (1 * ~one) * (1 * _3016225) == 1 * _432
        (1 * ~one) * (1 * _3016224) == 1 * _433
        (1 * ~one) * (1 * _3016223) == 1 * _434
        (1 * ~one) * (1 * _3016222) == 1 * _435
        (1 * ~one) * (1 * _3016221) == 1 * _436
        (1 * ~one) * (1 * _3016220) == 1 * _437
        (1 * ~one) * (1 * _3016219) == 1 * _438
         return 
  num variables: 2510353
  num constraints: 2611408
  num inputs: 1
  
  Finished setup at /app/code/gm17/ft-batch-transfer
  Running export-verifier at /app/code/gm17/ft-batch-transfer
  Error: Trusted setup failed: Error: export-verifier verifying key file not found
      at main (/app/code/index.js:246:13)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)

````
[logs]
````

**Comment by iAmMichaelConnor** [comment]
Hi @Genysys - thanks for opening this issue! It looks like the code has successfully compiled, but that possibly the zokrates container has 'fallen over' during the next step (the 'setup' step). Often this indicates that you don't have enough RAM (and swap) on your computer, or in your docker settings. How much RAM and swap have you allocated to Docker (in Docker's settings)?

**Comment by Genysys** [comment]
Thanks for the quick turning around. Here are my docker memory preferences.

Docker stats:

 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 10.24GiB
 Name: docker-desktop

Swap : 1.5 GB.


Thanks!

**Comment by Genysys** [comment]
Increased RAM + SWAP and works now!
