### ISSUE TITLE
Standardise naming conventions throughout Nightfall

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#337]
# Description

Some variable names can be confusing (e.g. single-letter names).
Some variables arise under different names depending on the function / microservice.

Suggest we think of how to standardise naming throughout.

@willKim19 made a good start.

E.g.:

```
inputCommitments: [
    {
        value, // or "amount" if preferred for fungibles. tokenId for non-fungibles.
        salt,
        publicKey,
        commitment,
        index,
        siblingPath,
        nullifier,
    },
    { ...
    }
]
```
```
outputCommitments: [
    {
        value, // or tokenId for non-fungibles
        salt,
        publicKey,
        commitment,
        index,
        siblingPath,
        nullifier,
    },
    { ...
    }
]
```

Names such as `C, D, E, F` for values aren't clear, and aren't generally applicable to multiple transfers at once (e.g. batching). Objects and arrays make things much clearer.

All microservices will need to be updated as a whole. The UI and database microservices are the best starting places, as these are the sources of data.

I'm open to other suggestions for structuring the naming :)

**Comment by iAmMichaelConnor** [comment]
E.g. no more `A`, `pk`, `C`, `S_A`, `z_A`, `z_A_index`.

We should be able to destructure objects from function to function without changing the name of the 'key' of the object.

E.g. from API-Gateway:
```
const burnFTCommitmentBody = {
      amount: req.body.A,
      receiverSecretKey: req.body.sk_A,
      salt: req.body.S_A,
      commitment: req.body.z_A,
      commitmentIndex: req.body.z_A_index,
      receiver: req.body.payTo || req.user.name,
    };
```

Also, objects such as `req.body` and `req.user` should really be destructured into key variables at the _beginning_ of a function. Repeatedly extracting `req.body.A` throughout a function feels messy. And `req.body` shouldn't be added to with extra info mid-way through a function - we should only be adding to `res.data`.

**Comment by vishnusudarshan** [comment]
Closing the issue since the PR created for this issue has been merged.
