### ISSUE TITLE
Remove folder ./docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#360]
# Description

It looks like the top-level folder `./docker-entrypoint-initdb.d` still exists. Is this used by anything? I recall this got moved to ./database/docker-entrypoint-initdb.d` (and indeed that folder also exists). 

Suggest removing the top-level folder (as long as it is indeed redundant).

**Comment by vishnusudarshan** [comment]
Closing the issue since the PR got merged to move the file from root directory
