### ISSUE TITLE
memory suggestions for docker not working

### ISSUE THREAD

**Issue by petscheit** [EYBlockchain/nightfall#383]
Hi,
tried generating the setup and wasn't able to so with 8GB of ram and 4GB swap. Zokrates setup step would silently fail for `ft-transfer.code` and then nightfall would throw an error, saying that `verification.key` can't be found.
I was able to generate this successfully with 12GB ram and 2GB swap. Please consider changing the documentation.

System:
macOS 10.15.1, 16GB ram
docker 2.2.0.3

**Comment by Mel-Marsollier** [comment]
I just tested it again with 8GB of ram with 4GB of swap space - did work system below. It is good to know that you made it work with the above ^^. 

System: 
macOS 10.14.6, 16GB ram
docker 2.1.1.0.5
