### ISSUE TITLE
run  transferFTCommitment failed!!!

### ISSUE THREAD

**Issue by xiaodu1993** [EYBlockchain/nightfall#413]
# Description
run  transferFTCommitment error!!!
<code>
{"error":"Generate proof failed: zokrates: /home/zokrates/src/target/release/build/zokrates_core-973919d5155c76b5/out/LIBSNARK/libsnark/relations/constraint_satisfaction_problems/r1cs/r1cs.tcc:136: bool libsnark::r1cs_constraint_system<FieldT>::is_satisfied(libsnark::r1cs_primary_input<FieldT>&, libsnark::r1cs_auxiliary_input<FieldT>&) const [with FieldT = libff::Fp_model<4, ((const libff::bigint<4>&)(& libff::alt_bn128_modulus_r))>; libsnark::r1cs_primary_input<FieldT> = std::vector<libff::Fp_model<4, ((const libff::bigint<4>&)(& libff::alt_bn128_modulus_r))>, std::allocator<libff::Fp_model<4, ((const libff::bigint<4>&)(& libff::alt_bn128_modulus_r))> > >; libsnark::r1cs_auxiliary_input<FieldT> = std::vector<libff::Fp_model<4, ((const libff::bigint<4>&)(& libff::alt_bn128_modulus_r))>, std::allocator<libff::Fp_model<4, ((const libff::bigint<4>&)(& libff::alt_bn128_modulus_r))> > >]: Assertion `primary_input.size() == num_inputs()' failed.\n"}
</code>

#### System information

Docker version:  Community 19.03.8
OS & Version: ubuntu16.0   4cpu 8g
Commit hash : master (b727865)

#### Expected behaviour
successfully run  

#### Actual behaviour
Failed

#### Backtrace

````
[backtrace]
````

#### Logs

````
[logs]
````

**Comment by xiaodu1993** [comment]
@magoon

**Comment by xiaodu1993** [comment]
@fulldecent  @magoon

**Comment by ChaitanyaKonda** [comment]
@xiaodu1993 Can you please more logging information and instructions on how you ran up application?

**Comment by iAmMichaelConnor** [comment]
> OS & Version: ubuntu16.0 4cpu 8g

This suggests possibly that you only have 8gb RAM on your machine; this might not be enough to run Nightfall's 'Setup'.

**Comment by Westlad** [comment]
Assumed solved as no further comments from @xiaodu1993.  Please reopen if not.
