### ISSUE TITLE
do not export directly from an import (airbnb strandards)

### ISSUE THREAD

**Issue by LijuJoseJJ** [EYBlockchain/nightfall#428]
# Description
import/export files: Although the one-liner is concise, having one clear way to import and one clear way to export makes things consistent.

#### System information

Docker version: `docker version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
https://github.com/airbnb/javascript#modules--no-export-from-import

#### Actual behaviour
`
export { default as rootRouter } from './api-gateway';
export { default as nftCommitmentRoutes } from './nft-commitment';
`

**Comment by Westlad** [comment]
PR merged
