### ISSUE TITLE
Need Windows Support

### ISSUE THREAD

**Issue by walter-grace** [EYBlockchain/nightfall#45]
I tried to run this on windows 10; I was having issues getting docker-proxy start to run. I know there is an open issue, and @aj-may needs Windows 10 to his docker-proxy code. 

_@mkinney 
"The docker-proxy solution does not work on Ubuntu. @aj-may is trying to see if we can use something else. Tried using dotproxy, and it almost works. All builds, but the docker instances just do not see themselves. So, when you try to create a user thru the UI, the UI errors."_

If anyone has any ideas or work arounds, I am up to try them.

**Comment by ocgordon** [comment]
@walter-grace We've identified [dory](https://github.com/FreedomBen/dory/) as a potential workaround for docker-proxy on Ubuntu in #20 , and I believe @aj-may is working on [dotdocker](https://github.com/aj-may/dotdocker) as another workaround for Linux. I'll give it a shot today

**Comment by aj-may** [comment]
@walter-grace I would be interested on working to add windows support to [dotdocker](https://github.com/aj-may/dotdocker), but I would need some help as I don't have a windows machine and haven't touched it in years.

The challenge on windows is configuring the custom dns server for the `.docker` TLD.  There is some info here: https://github.com/codekitchen/dinghy-http-proxy#windows

**Comment by Westlad** [comment]
Just to be clear, we're not intending to support Windows, although we're very happy if someone wants to take that on.

**Comment by walter-grace** [comment]
> The challenge on windows is configuring the custom dns server for the `.docker` TLD. There is some info here: https://github.com/codekitchen/dinghy-http-proxy#windows

I will try and work on this; I have Windows10 hardware I can plug and play with @aj-may. If I get it running I will add @Westlad
