### ISSUE TITLE
Needs Linux support 

### ISSUE THREAD

**Issue by outkaj** [EYBlockchain/nightfall#46]
# Description

As discussed in #28 docker-proxy does not work on Ubuntu (or other Linux distros) yet. 

#### System information

Docker version: `18.09.6` 
OS & Version: Ubuntu 18.04.2 LTS 

#### Expected behaviour

I would expect `./zkp-demo` to run successfully.

#### Actual behaviour

Running `./zkp-demo` on Ubuntu machine produces a backtrace (see below). 

#### Steps to reproduce the behaviour

Configure Nightfall as described in setup and try to run.

#### Backtrace

```
ERROR: for nightfall_ganache_1  Cannot start service ganache: driver failed programming external connectivity on endpoint nightfall_ganache_1 (cd14b6eb1415a5810e60d8ec360fb1743568bcfe09f129603551609f9ad3d026): Error starting userland proxy: 

ERROR: for ganache  Cannot start service ganache: driver failed programming external connectivity on endpoint nightfall_ganache_1 (cd14b6eb1415a5810e60d8ec360fb1743568bcfe09f129603551609f9ad3d026): Error starting userland proxy: 
ERROR: Encountered errors while bringing up the project.
```

**Comment by ocgordon** [comment]
@outkaj Have you tried using `dotdocker`? @aj-may mentioned that he was able to use it as a workaround in #20

**Comment by outkaj** [comment]
thank you! I'll take a look

**Comment by outkaj** [comment]
I was able to get nightfall docker-compose up and running using `dory` as discussed in #20. Closing
