### ISSUE TITLE
docker-proxy issues

### ISSUE THREAD

**Issue by AndreiD** [EYBlockchain/nightfall#5]
followed the initial steps. Everything ...OK
reached:
~~~~
 We're ready to go! Run the demo:
./zkp-demo
~~~~

it gets stuck at 

![b1](https://user-images.githubusercontent.com/542665/58725439-c8240a80-83e7-11e9-869a-e15e9fcd7651.png)

going to http://nightfall.docker give not found, and going to http://localhost:80 gives an empty apache page

**Comment by aj-may** [comment]
Have you setup and started `docker-proxy`? If so, can you provide the output of `docker ps` to make sure the proxy container was started and is running without errors?

**Comment by AndreiD** [comment]
yes.

~~~~
 docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS              PORTS                    NAMES
ef290cbc80bb        nightfall_database                "/bin/sh -c 'npm sta…"   About a minute ago   Up About a minute   80/tcp                   nightfall_database_1
2a6eefc96b96        nightfall_accounts                "/bin/sh -c 'npm sta…"   About a minute ago   Up About a minute   80/tcp                   nightfall_accounts_1
dc90ef5e3adf        nightfall_offchain                "/bin/sh -c 'npm sta…"   About a minute ago   Up About a minute   80/tcp                   nightfall_offchain_1
562d8496a9a9        mongo                             "docker-entrypoint.s…"   About a minute ago   Up About a minute   27017/tcp                nightfall_mongo_1
e0520ac5386d        nightfall_zkp                     "/bin/sh -c 'npm sta…"   About a minute ago   Up About a minute   80/tcp                   nightfall_zkp_1
3bba5be47b42        nightfall_ui                      "/bin/sh -c 'npm sta…"   About a minute ago   Up About a minute   80/tcp                   nightfall_ui_1
56b5c32aef40        nightfall_api-gateway             "/bin/sh -c 'npm sta…"   About a minute ago   Up About a minute   80/tcp                   nightfall_api-gateway_1
3cc87f390b4d        trufflesuite/ganache-cli:latest   "node /app/ganache-c…"   About a minute ago   Up About a minute   0.0.0.0:8545->8545/tcp   nightfall_ganache_1
184186c001a2        michaelconnor/zok:2Jan2019        "/bin/bash -c 'tail …"   About an hour ago    Up About an hour                             nifty_easley
fae0deefa30e        michaelconnor/zok:2Jan2019        "/bin/bash -c 'tail …"   About an hour ago    Up About an hour                             heuristic_nash
c09ee9eebeb8        michaelconnor/zok:2Jan2019        "/bin/bash -c 'tail …"   About an hour ago    Up About an hour                             zen_tereshkova
d656300cfd3c        michaelconnor/zok:2Jan2019        "/bin/bash -c 'tail …"   About an hour ago    Up About an hour                             zealous_elion
eca2435693fe        michaelconnor/zok:2Jan2019        "/bin/bash -c 'tail …"   About an hour ago    Up About an hour                             agitated_brattain
378fbae388d5        michaelconnor/zok:2Jan2019        "/bin/bash -c 'tail …"   About an hour ago    Up About an hour                             epic_mayer
~~~~~

**Comment by aj-may** [comment]
So it looks like the proxy container is not running.  If it was you would see something like this in the output:
```
3d8339c2d8ff        codekitchen/dinghy-http-proxy   "/app/docker-entrypo…"   2 days ago          Up 24 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 19322/tcp, 0.0.0.0:19322->19322/udp   http-proxy
```

Try running `docker-proxy start`.  If you get an error post it here and I can help walk you through it.

**Comment by AndreiD** [comment]
Thanks for the very fast message.
docker-proxy start doesn't do anything.. It doesn't start any container so the docker ps remains the same.
I'll do some google-ing to see why this happens.

Ubuntu 19.04

**Comment by aj-may** [comment]
A few things to check:
- Make sure the `docker-proxy` script is on your `PATH`.  An easy way to do this is to run the install script from within `/usr/local/bin`
- To check to see if the container started but exited, run `docker ps -a` to show stopped containers

Additionally, the `docker-proxy` script has only been tested on MacOS, however I don't think there should be any major differences running on Ubuntu.  The script just makes it easier to run the `dinghy-http-proxy` image.   If you want you can try running that image without the script by following the instructions here <https://github.com/codekitchen/dinghy-http-proxy#linux>.

**Comment by AndreiD** [comment]
some strange things...while running docker-proxy start I didn't get any warnings of "command not found" or else... so I reinstalled it. copy it to /usr/local/bin

but now on running start
~~~~
sudo docker-proxy start
Starting container...
Error response from daemon: driver failed programming external connectivity on endpoint http-proxy (2b6d1abfe30528b72a5618069eabf6fca22f695c525a7554443567fb7c224413): Error starting userland proxy:
Error: failed to start containers: http-proxy
~~~~

**Comment by aj-may** [comment]
This is a bit of a shot in the dark, but do you have anything already listening on port 80?

**Comment by AndreiD** [comment]
so for some reason apache2 is constantly starting on port 80. I purged it, run docker-proxy start, 
now

~~~~
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                           NAMES
8fc6ed9ad9c7        nightfall_database                "/bin/sh -c 'npm sta…"   2 minutes ago       Up 2 minutes        80/tcp                                                                          nightfall_database_1
95f73ecdc931        nightfall_offchain                "/bin/sh -c 'npm sta…"   2 minutes ago       Up 2 minutes        80/tcp                                                                          nightfall_offchain_1
892199080b39        nightfall_accounts                "/bin/sh -c 'npm sta…"   2 minutes ago       Up 2 minutes        80/tcp                                                                          nightfall_accounts_1
9c214bde62b1        nightfall_zkp                     "/bin/sh -c 'npm sta…"   2 minutes ago       Up 2 minutes        80/tcp                                                                          nightfall_zkp_1
891b9df5ce1e        nightfall_api-gateway             "/bin/sh -c 'npm sta…"   2 minutes ago       Up 2 minutes        80/tcp                                                                          nightfall_api-gateway_1
6c3f04821a0c        mongo                             "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        27017/tcp                                                                       nightfall_mongo_1
0b167bfb8723        nightfall_ui                      "/bin/sh -c 'npm sta…"   2 minutes ago       Up 2 minutes        80/tcp                                                                          nightfall_ui_1
3d0e91650cf6        trufflesuite/ganache-cli:latest   "node /app/ganache-c…"   3 minutes ago       Up 3 minutes        0.0.0.0:8545->8545/tcp                                                          nightfall_ganache_1
8c2d2dfb665b        codekitchen/dinghy-http-proxy     "/app/docker-entrypo…"   15 minutes ago      Up 3 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 19322/tcp, 0.0.0.0:19322->19322/udp   http-proxy

~~~~

on http://nightfall.docker/ is page not found
on http://localhost I get "Welcome to the Dinghy HTTP Proxy"

**Comment by aj-may** [comment]
Ah, that will do it.  Apache must have been listening.

Looks like your really close.  There's 3 things that might still not be working right:
- The `dinghy-http-proxy` image configures Nginx to route traffic to the correct containers by listening for events on the docker socket.  Since you started the application containers first, it may not have had a chance to register the containers.
- You OS might not be querying the DNS server that runs inside `dinghy-http-proxy` to resolve the `.docker` TLD
- The DNS lookup may have been cached somewhere along the way

I would start by restarting your computer as this will have the effect of restarting all the containers which can fix scenario one, but also is sometimes required to get the OS to start querying the new DNS server (scenario two).

To test the last scenario, try using a private browsing window or clearing cache.

**Comment by AndreiD** [comment]
I'm going to close this issue since it's not related to this project.
I get

Error response from daemon: driver failed programming external connectivity on endpoint http-proxy (d023b5ae863f8341fe4673ddde2e430b854594703798413695eb00fdbd3e888f): Error starting userland proxy:.

when trying to start 

~~~~
docker run -d --restart=always \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  -v ~/.dinghy/certs:/etc/nginx/certs \
  -p 80:80 -p 443:443 -p 19322:19322/udp \
  -e CONTAINER_NAME=http-proxy \
  --name http-proxy \
  codekitchen/dinghy-http-proxy
~~~~

some people are suggesting restarting docker, but this doesn't seem to help.

Is there any workaround I can view the Angular UI without using docker-proxy ?

**Comment by AndreiD** [comment]
test with ->

docker run -d --restart=always -v /var/run/docker.sock:/tmp/docker.sock:ro -v ~/.dinghy/certs:/etc/nginx/certs -e CONTAINER_NAME=http-proxy --name http-proxy codekitchen/dinghy-http-proxy

CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
da8083262360        codekitchen/dinghy-http-proxy   "/app/docker-entrypo…"   35 seconds ago      Up 33 seconds       80/tcp, 19322/tcp   http-proxy

**Comment by AndreiD** [comment]
thanks to https://github.com/Solexplorer
