### ISSUE TITLE
Publish security advisories to GitHub security section

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#51]
GitHub has a specific section dedicated to security advisories.

Please copy the items from https://github.com/EYBlockchain/nightfall/blob/master/security-updates.md to https://github.com/EYBlockchain/nightfall/security/advisories

Currently, the benefit is that the Security page will have better information on it. In the future there may be additional benefits. For example, GitHub may ping people that subscribe to a repository when security updates are announced in that way.

**Comment by Mel-Marsollier** [comment]
Hey @fulldecent

I do not have the proper access right to do it myself but I believe it should be done shortly. Thank you for pointing this out! Will update when it’s done :).

**Comment by iAmMichaelConnor** [comment]
https://github.com/EYBlockchain/nightfall/security/advisories/GHSA-36j7-5gjq-gq3w

@fulldecent thanks for this suggestion - please see here
