### ISSUE TITLE
Update link to docker-proxy

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#52]
The README.md currently links to docker-proxy. [According to its author](https://github.com/aj-may/docker-proxy/), this package has been rewritten and rereleased as dotdocker at https://github.com/aj-may/dotdocker/blob/master/README.md.

The new version has an install path that is safer (does not require `curl ... | bash`) and integrates with one of our existing tools (npm) so this may be preferred.

**Comment by ocgordon** [comment]
Closing this issue, as the link has been updated to dotdocker.
