### ISSUE TITLE
First time Minted EYOpscoin disappears

### ISSUE THREAD

**Issue by skradha26** [EYBlockchain/nightfall#59]
Steps to recreate the issue:

1. Open url "http://nightfall.docker" in a browser
2. Click on Mint OpsCoin and enter a value
3. Open a private window in the browser and create a second account. login to the second account.
4. Go back to the window opened initially. 
5. Click on Mint OpsCoin Commitment.
6. I get the error "Not enough Public coin..."

Note: Coins do not disappear after creating for the second time.

Did anyone face this issue? I haven't checked Mint EYToken. So, I am not sure if there is a simialr issue in there too.

# Description

#### System information

Docker version: `docker version`
OS & Version: OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by asishap** [comment]
@skradha26 
We could n't reproduce this issue. Which browser you have used ? Also if you are still facing the same issue could you please provide the proper logs ?

**Comment by skradha26** [comment]
After i downloaded the latest code from github, issue didnt reappear. Thanks
