### ISSUE TITLE
About packedToBytes27 function in FTokenShield.sol

### ISSUE THREAD

**Issue by BlockHeader** [EYBlockchain/nightfall#62]
function packedToBytes27(uint256 low, uint256 high) private pure returns (bytes27){
    return bytes27(uint216(low)) | (bytes27(uint216(high))<<**128**);
  }

Whether the 103 (216/2), not 128 should be left-shifted?

**Comment by Westlad** [comment]
Hi @BlockHeader.  Apologies for the delay in my reply.  This is because the function is unpacking a 216 bit number that has been packed into two 128 bit fields for the ZoKrates DSL code.

**Comment by BlockHeader** [comment]
Dear Duncan, 


       Glad to hear your response. Thanks a lot for your explanation about function. 


       I have another question in mind: why EYBlockchain uses the out-band secret distribution, not in-band distribution (as Zcash)? 


       Thanks a lot :)


   Star.LI
July.15 2019




------------------ 原始邮件 ------------------
发件人: "Duncan Westland"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 下午4:13
收件人: "EYBlockchain/nightfall"<nightfall@noreply.github.com>;
抄送: "xingmm"<2841133010@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [EYBlockchain/nightfall] About packedToBytes27 function inFTokenShield.sol (#62)




Hi @BlockHeader.  Apologies for the delay in my reply.  This is because the function is unpacking a 216 bit number that has been packed into two 128 bit fields for the ZoKrates DSL code.

**Comment by Westlad** [comment]
@BlockHeader we were keen to experiment with Whisper to see if it would work for this.

**Comment by Westlad** [comment]
Please feel free to re-open if you have further questions.
