### ISSUE TITLE
Ftoken.transfer and approve will always return false (Slither result)

### ISSUE THREAD

**Issue by montyly** [EYBlockchain/nightfall#7]
Hi,

We run our set of private [Slither](https://github.com/EYBlockchain/nightfall/blob/master/zkp/contracts/FToken.sol#L191-L193) detectors on the codebase, and found that `Ftoken.transfer` and `approve` will always return false, leading to broken interactions with third-party contracts.

## Description

Both functions return a boolean, but have no return statement. As a result, `False` will be returned

https://github.com/EYBlockchain/nightfall/blob/9fbd1f4f2e41d246f85dac910da35223b8f3a5d0/zkp/contracts/FToken.sol#L171-L173

https://github.com/EYBlockchain/nightfall/blob/9fbd1f4f2e41d246f85dac910da35223b8f3a5d0/zkp/contracts/FToken.sol#L191-L193

Any ERC20 interaction from an external contract is likely to be impossible, as the caller will check for the correct return (see the [ERC20 documentation](https://eips.ethereum.org/EIPS/eip-20))  

## Fixes

Return the value returned by `_approve` and `_transfer`

**Comment by 1blockologist** [comment]
Can you submit a PR that references this issue?
