### ISSUE TITLE
Initial ERC-721 Commitment Not Transferring

### ISSUE THREAD

**Issue by ocgordon** [EYBlockchain/nightfall#74]
# Description
When transferring ERC-721 token commitments, the first commitment does not show up as received for the recipient. Subsequent transferred commitments show up without issue, but there is no record in the recipient account of having received the first commitment.

#### System information

Docker version: `2.0.0.3`
OS & Version: OSX 10.14.5
Commit hash : `e587d33`

#### Expected behaviour
The first transferred ERC-721 token commitment shows up in the inventory of the recipient along with subsequent received commitments.

#### Actual behaviour
The first transferred ERC-721 token commitment does not show up in the inventory of the recipient, but subsequent transferred commitments do show up. 

#### Steps to reproduce the behaviour
1. Create two accounts "Tom" and "Jerry"
2. "Tom" mints an ERC-721 token
3. "Tom" mints an ERC-721 token commitment
4. "Tom" transfers this ERC-721 token commitment to "Jerry"
5. "Jerry" logs in and has received  the ERC-721 token commitment

**Comment by ChaitanyaKonda** [comment]
Closed as unable to replicate
