### ISSUE TITLE
Cannot capitalize accountName when creating account

### ISSUE THREAD

**Issue by crawfordleeds** [EYBlockchain/nightfall#76]
# Description

I had some issues creating an account yesterday, which I documented as a comment on issue #13. Specifically, when I tried to create a new account I received an error with message "Command failed: mongo nightfall --host=mongo -u admin -p admin script_to_configure_roles.js\n"

I now think the errors received yesterday are due to capitalization in the `accountName` field on signup. I haven't yet identified the code that would verify my suspicion, but I have been able to replicate the issue by repeatedly receiving the same error when creating an account with any capitalization in the `accountName` and not receiving any errors when using no capitalization in the `accountName`.

If anyone else is able to replicate the issue, I'd be happy to make a note in the README so that others don't get stuck as I did. Alternatively, I can dig into the code a bit to see I can find why it doesn't seem to like capitalization.

#### System information

Docker version: `2.0.0.3`
OS & Version: OSX 10.15.4
Commit hash : e587d335d8e8b47e3bb4e6d3f0b2ef81054ff557 (master)

#### Expected behaviour

I would expect a user to be able to enter their full name without character restrictions, except perhaps a character limit or special character restriction, which does not seem to be implemented either.

#### Actual behaviour

I discovered no additional restrictions on spaces or special characters, but capitalization (in any location in the `accountName` string) triggers the error described above.

#### Steps to reproduce the behaviour

1. See README for setup
2. Navigate to http://nightfall.docker/createAccount in a browser (I was using Chrome)
3. Complete the fields as follows:
- Your full name: 'a'
- Enter email: 'a'
- Pass Phrase: 'password'
- Confirm Pass Phrase: 'password'
4. Click 'CREATE ACCOUNT'

This should work successfully. To trigger the error, follow those four step again but replace the fields with the following:

- Your full name: 'B'
- Enter email: 'B'
- Pass Phrase: 'password'
- Confirm Pass Phrase: 'password'

Note, you should be able to use whatever email and password you want. I did this a number of times over and didn't' find any character restrictions for the email, password, or password confirmation fields.

Additionally, I found that in some cases, once this error was triggered, there was no way to create an account with a valid accountName. For example, if I tried to create another account with full name as 'c', email as 'c', password and password confirmation as 'password', I would sometimes get the same error as if I submitted the form with a capitalized name. I couldn't replicate this 100% of the time, but I'm suspicious it has something to do with dotdocker because it seemed that restarting dotdocker would sometimes stop this issue of the error carrying forward to later post requests.

#### Backtrace

It's long so I have attached it here: [logfile.txt](https://github.com/EYBlockchain/nightfall/files/3390316/logfile.txt)

Here are some of what I think are the most important lines:

**Line 960**: Completed compilation and deployment
**Line 960**: Start account creation process with name="a", email="a", password="password", password_confirmation="password". This was successful.
**Line 1122**: Error on signup due to capitalization of name. Used params, name="B", email="B", password="password", password_confirmation="password".
**Line 1213**: This is the start of the same error, despite now using an all lowecase name, "c". Note, I do not think this has anything to do with repeated attempts because I went through a few times testing 5+ accounts in a row with all lower case names and had no issues.

**Comment by ocgordon** [comment]
After some testing, I found that uppercase and special characters are invalid for the name, email, and password fields. A capital letter or special character in any of these fields results in the same error (similar to below) for me, which is consistent with your error.
```
database_1          | error: POST:/createAccount
database_1          | 		{"error":"Command failed: mongo nightfall --host=mongo -u admin -p admin script_to_configure_roles.js\n"}
database_1          | 		{"body":{"name":"b","email":"test@ey.com","password":"aaa","address":"address","shhIdentity":""}}
database_1          | 		{"params":{}}
database_1          | 		{"query":{}}
database_1          |
api-gateway_1       | error: POST:/createAccount
api-gateway_1       | 		{"error":"Command failed: mongo nightfall --host=mongo -u admin -p admin script_to_configure_roles.js\n"}
api-gateway_1       | 		{"body":{"name":"b","email":"test@ey.com","password":"aaa"}}
api-gateway_1       | 		{"params":{}}
api-gateway_1       | 		{"query":{}}
api-gateway_1       |
database_1          | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

Looks like it could be an issue with mongo configuration since we both also have: 
```
mongo_1             | 2019-07-15T20:00:34.800+0000 E -        [main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: Unknown error
```

**Comment by crawfordleeds** [comment]
@ocgordon, thanks for letting me know I'm not the only one with an issue here. Although, I didn't have issues with capital letters or special characters in the email fields (I didn't try varying the password field). For example, I created an account with the email test@test.com with name 'a' and had no issues.

I only just saw the "Error saving history...." message, nice catch. However, that only seems to appear for me after successful new account creation, not after the error originally mentioned above.

This seems to be the line that triggers the error. Do you know why this is executed as a script rather than as part of the DB methods like in the addUser method?
https://github.com/EYBlockchain/nightfall/blob/e587d335d8e8b47e3bb4e6d3f0b2ef81054ff557/database/src/mongodb/db.js#L182

Might be way off here but I had a thought that maybe this is an encoding issue in `exec()`, which can be configured as an option as shown [here](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

**Comment by ocgordon** [comment]
@crawfordleeds we both have the "Error saving history..." message before attempting account creation, so I'm thinking an issue with the initial mongo setup like you mentioned. I'll investigate this line.

**Comment by crawfordleeds** [comment]
Oh, you're completely right on the error message location, sorry about that.

Let me know if there's anything in particular I can do to help.

**Comment by cmumby** [comment]
@ocgordon @crawfordleeds I do notice that mongo does create the user and adds it to the db--even though I get the same error messages. When I list users from the `nightfall_mongo_1` container after attempting to generate names with capital letters I got:
```
> db.getUsers();
[
        {
                "_id" : "nightfall.Bigcap",
                "user" : "Bigcap",
                "db" : "nightfall",
                "customData" : {

                },
                "roles" : [
                        {
                                "role" : "read",
                                "db" : "nightfall"
                        }
                ]
        },
        {
                "_id" : "nightfall.Testname",
                "user" : "Testname",
                "db" : "nightfall",
                "roles" : [
                        {
                                "role" : "userAdmin",
                                "db" : "nightfall"
                        },
                        {
                                "role" : "dbAdmin",
                                "db" : "nightfall"
                        },
                        {
                                "role" : "readWrite",
                                "db" : "nightfall"
                        }
                ]
        },
        {
                "_id" : "nightfall.Testwithcapital",
                "user" : "Testwithcapital",
                "db" : "nightfall",
                "customData" : {

                },
                "roles" : [
                        {
                                "role" : "read",
                                "db" : "nightfall"
                        }
                ]
        },
        {
                "_id" : "nightfall.admin",
                "user" : "admin",
                "db" : "nightfall",
                "roles" : [
                        {
                                "role" : "userAdmin",
                                "db" : "nightfall"
                        },
                        {
                                "role" : "dbAdmin",
                                "db" : "nightfall"
                        },
                        {
                                "role" : "readWrite",
                                "db" : "nightfall"
                        }
                ]
        }
]
```
However, I am unable to sign on with any of the created users.

**Comment by crawfordleeds** [comment]
@cmumby I had the same experience. In your example, did the user id "Testname" allow you to login? It seems that has the expected read/write and admin roles, despite the capitalization in the name.

**Comment by cmumby** [comment]
@crawfordleeds I tried again to make sure--the user `Testname` wasn't able to log on despite having the correct roles.

**Comment by crawfordleeds** [comment]
Odd, that seems to draw more questions than it answers.

**Comment by asishap** [comment]
@crawfordleeds @cmumby @ocgordon 

Thank you for investigating this issue. 

In nightfall we are dynamically creating collections based on user name. Every user have their own collections and collections name would be prefixed with his/her username. We observed that mongo does n't allow to create collection name with capital letters and it automatically changes the name to lower case. So during the account creation we are applying ACL to the mongo collections based on user name and mongo could n't recognise the collection name with small letters.

**Comment by ocgordon** [comment]
@asishap Are you able to use @ in the email field? I have been able to create an account using an email with an @, but I receive the error message and am unable to log into the created account.

**Comment by asishap** [comment]
@ocgordon Yes am able to create account using @ in the email field and login that account. Are you using email to login ? 
Soon I will give a PR for fix to restrict capital letters and special characters in username field.

**Comment by ChaitanyaKonda** [comment]
Resolved
