### ISSUE TITLE
NFTokenShield._owner shadows Ownable._owner (Slither result)

### ISSUE THREAD

**Issue by montyly** [EYBlockchain/nightfall#8]
Hi,

Another issue reported by [Slither](https://github.com/crytic/slither) is the shadowing of the `_owner` variable in `NFTokenShield`, leading to an incorrect ownership schema.

## Description 

`NFTokenShield._owner` shadows `Ownable._owner`

https://github.com/EYBlockchain/nightfall/blob/9fbd1f4f2e41d246f85dac910da35223b8f3a5d0/zkp/contracts/NFTokenShield.sol#L53

https://github.com/EYBlockchain/nightfall/blob/9fbd1f4f2e41d246f85dac910da35223b8f3a5d0/zkp/contracts/Ownable.sol#L17

As a result, `NFTokenShield` will have two `_owner` variables. The modifier `onlyOwner` and the function `transferOwnership` will be performed using `Ownable._owner`, while `close()` will be performed using `NFTokenShield._owner`.

## Fix
- Remove `NFTokenShield._owner`, or 
- Rename `NFTokenShield._owner` to avoid confusion (If the goal is to have two separate variables).

**Comment by 1blockologist** [comment]
Can you submit a PR?
