### ISSUE TITLE
Add ZoKrates Dockerfile to this repository

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#89]
The docker image michaelconnor/zok:2Jan2019 is unavailable for inspection and so it cannot be evaluated. Please add that Dockerfile into this project or open source it as a separate project.

**Comment by ChaitanyaKonda** [comment]
The Dockerfile is the one from this [commit](https://github.com/Zokrates/ZoKrates/tree/8595434d19f0502c0c40e09c68bda894e3bdfbe8) of ZoKrates on 2 Jan 2019.

**Comment by fulldecent** [comment]
Is there a reason that a specific release from https://hub.docker.com/r/zokrates/zokrates/tags was not preferred?
