### ISSUE TITLE
Remove dependency on dot docker for non-developers

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#90]
# Description

Currently dot docker is required for all users. This unnecessary requires an additional installation step for every user.

#### System information

Docker version: 18.09.2
OS & Version: macOS
Commit hash : 82557c8e78002f66c61e50937cd5eb6485b09d90

#### Expected behaviour

Users can install and run Nightfall without dot docker.

#### Actual behaviour

Every user is required to use dot docker.

#### Steps to reproduce the behaviour

1. Follow instructions in README.md to install and run Nightfall.

**Comment by ChaitanyaKonda** [comment]
It is required for every user. It acts as a docker proxy service

**Comment by ChaitanyaKonda** [comment]
Closed

**Comment by ChaitanyaKonda** [comment]
Reopened

**Comment by ChaitanyaKonda** [comment]
#117 PR has been merged. Solves this issue
